# SSH Deploy

name: SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: SSH deployment every commit
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Install packages
      uses: actions/setup-node@v3
      with:
        node-version: 18
        #cache: "npm"
    #- run: npm ci
    
    - name: Install npm dependencies
      run: npm install

    - name: Build project
      run: npm run build --if-present
      env:
        CI: false

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa.pub
        ssh-keyscan -H ${{ secrets.SFTP_SERVER }} >> ~/.ssh/known_hosts
        
    - name: Transfer / Copy builds to server
      run: |
        rsync -vrm ./build/* ${{ secrets.SFTP_USER }}:${{ secrets.REMOTE_TARGET }}
